import type { Submission, User } from "@/lib/types";

export const users: User[] = [
  { id: "user1", name: "Dawit Abebe", role: "User" },
  { id: "user2", name: "Fatima Yusuf", role: "User" },
  { id: "approver1", name: "Dr. Selamawit", role: "Approver" },
];

export const initialSubmissions: Submission[] = [
  {
    id: "sub1",
    userId: "user1",
    userName: "Dawit Abebe",
    status: "Approved",
    submittedAt: new Date("2024-03-15T09:30:00Z").toISOString(),
    lastModifiedAt: new Date("2024-03-20T14:00:00Z").toISOString(),
    comments: "Good proposal. Approved.",
    projectTitle: "የክትባት ምርምር ፕሮጀክት",
    department: "it",
    goal: "goal1",
    objective: "obj1",
    strategicAction: "በሽታን መዋጋት",
    metric: "የበሽታ መቀነስ",
    mainTask: "ሙከራ ማካሄድ",
    mainTaskTarget: "1000 ተሳታፊዎች",
    objectiveWeight: "5",
    strategicActionWeight: "4",
    metricWeight: "3",
    mainTaskWeight: "5",
    executingBody: "internal",
    executionTime: "q1",
    budgetSource: "gov",
    governmentBudgetAmount: "500000",
    governmentBudgetCode: "code1"
  },
  {
    id: "sub2",
    userId: "user2",
    userName: "Fatima Yusuf",
    status: "Pending",
    submittedAt: new Date("2024-04-01T11:00:00Z").toISOString(),
    lastModifiedAt: new Date("2024-04-01T11:00:00Z").toISOString(),
    projectTitle: "የቲቢ ስርጭት ትንተና",
    department: "finance",
    goal: "goal2",
    objective: "obj2",
    strategicAction: "የጄኔቲክ ካርታ መስራት",
    metric: "የተለያዩ ስርጭቶችን መለየት",
    mainTask: "ናሙና መሰብሰብ",
    mainTaskTarget: "500 ናሙናዎች",
    objectiveWeight: "4",
    strategicActionWeight: "5",
    metricWeight: "4",
    mainTaskWeight: "3",
    executingBody: "internal",
    executionTime: "q2",
    budgetSource: "grant",
    grantBudgetAmount: "120000"
  },
  {
    id: "sub3",
    userId: "user1",
    userName: "Dawit Abebe",
    status: "Rejected",
    submittedAt: new Date("2024-04-10T16:20:00Z").toISOString(),
    lastModifiedAt: new Date("2024-04-12T10:05:00Z").toISOString(),
    comments: "Budget exceeds department limits. Please revise and resubmit.",
    projectTitle: "የኤችአይቪ/ኤድስ ማህበረሰብ ግንዛቤ",
    department: "hr",
    goal: "goal1",
    objective: "obj1",
    strategicAction: "ግንዛቤ ማስጨበጥ",
    metric: "የምርመራ መጠን መጨመር",
    mainTask: "ዎርክሾፕ ማካሄድ",
    mainTaskTarget: "5 ዎርክሾፖች",
    objectiveWeight: "5",
    strategicActionWeight: "5",
    metricWeight: "5",
    mainTaskWeight: "5",
    executingBody: "external",
    executionTime: "q3",
    budgetSource: "sdg",
    sdgBudgetAmount: "75000"
  },
];
